# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true

markdown: redcarpet
searchindex: yes
production_url : http://sravan.me # or your custom domain name
title : A Sravan Kumar

author :
name : A Sravan Kumar
email : asravan2007@gmail.com
github : asravankumar
twitter : asravan_kumar
